version: '3.3'
services:
  nginx:
    image: nginx
    container_name: formproj_nginx
    volumes:
       - ./wordpress:/var/www/html
       - ./nginx/formproj-dev.tszsol.com.conf:/etc/nginx/conf.d/formproj-dev.tszsol.com.conf
#       - ./prod-nginx.conf:/etc/nginx/nginx.conf
       - ./logs/:/var/log/nginx/
       - ./ssl/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
    links:
      - wordpress
    restart: always
    networks:
      - formproj_net
    environment:
      - NGINX_HOST=formproj-dev.tszsol.com

  db:
    container_name: formproj_mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql:/docker-entrypoint-initdb.d"
    networks:
      - formproj_net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: formproj_pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  wordpress:
    build:
      context: wordpress
      dockerfile: ../php/Dockerfile
    container_name: formproj_wp
    depends_on:
      - db
    env_file:
      - .env
    environment:
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_HOME', '$WP_HOME');
          define('WP_SITEURL', '$WP_SITEURL');
          define('FS_METHOD', 'direct');
          set_time_limit(600);
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
      XDEBUG_CONFIG: "remote_host=${OWN_IP}"
      #   image: wordpress:5.8-php7.4-fpm
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - "./wordpress:/var/www/html/"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    networks:
      - formproj_net
networks:
  formproj_net:
    driver: "bridge"
volumes:
  db_data: ~
